### ISSUE TITLE
some kinda of weird fly bypass bug idk

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#10]
if your elytraing then turn fly on a client even when the elytras stop elytraing you can still fly infinitly but heres a video of it https://streamable.com/hwhnp

**Comment by Olexorus** [comment]
I don't think it's really possible to draw a clear line between flying and falling while using an elytra (if you have an elytra, as long as you're in the air, you can always start gliding), so basically the only way to block this will be to write an elytra fly check, which I have planned, but probably not in the next few updates.

**Comment by Olexorus** [comment]
Since there was a pretty big pause in WACs development I've decided to close all currently open issues. A bug list for an Anti Cheat will never be complete anyways, so I'd rather only have the things I'm plannign to work on soon on the issue tracker.
If this issue still exists on the latest version and you think it's important for me to fix you can of course reopen it.
