### ISSUE TITLE
Reach False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#24]
sometimes when a ghast shoots a fireball at you and you hit it back sometimes it falses reach https://streamable.com/0w63n

**Comment by Olexorus** [comment]
Yeah, it's because the fireball is moving pretty quickly, and there's always a certain delay between client and server. However the ping isn't relieable enough to use it in calculations, and there are other factors that play into this, so all I can do is add a certain lenience and try to find a good balance between stopping false positives and blocking hacks, and I believe my current values are alright.
