### ISSUE TITLE
checks to rename

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#27]
rename packet speed to timer sense timer flags packet speed and it should be instead called timer you should remove the blocked hacks list in the spigotmc page of the onground speed detection sense speed would detect that anyway rename water walk to just jesus rename climb to spider and remove the bhop detection hack on the list on spigotmc sense speed would detect that heres my version of the spigotmc page cause idk
Blocked hacks: 
Killaura
Fly
Speed
Blink
Nofall
Step
Reach
Jesus
Pingspoof
Spider
that should be the list instead of adding stuff in the detection list that the other checks detect

**Comment by Olexorus** [comment]
Imo spider is just a weird name for fast climb, the same applies to jesus and water walk.

I can't actually detect timer hacks. I can detect that a client is sending packets too quickly, which is often a result of a timer hack, but can also have other causes, so it doesn't make any sense to guess what the hack might be called, I'll just give clear info why the detection was triggered. Besides the same hacks can have different names in different clients.

And imo there's a difference between normal vanilla speed hacks, and bhop or onground speed hacks, they work differently, that's why they're listed seperately.
