### ISSUE TITLE
improved config (that i use)

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#28]
i removed the notification delay sense it was 20 seconds so i almost never see alerts i removed the notification threshold sense after the next update most falses will be fixed so i dont see a reason for the delay added the server tps check and turned on the kick i would make it so it would autoban but no option for that and the tps check is 10 tps sense once a servers at 10 tps thats when it starts to make players teleport around bug etc removed the notification expiration sense i dont see why i would want that to be removed make a option so you can set that to -1 so you never get expiration and if that already is a option make a disclaimer there so if you want to never have notification expiration set it to -1 and i didn't add a ping check sense some people can use pingspoof then bypass some checks and idk if the pingspoof check detects every pingspoof module so i didn't check for it and near the top where it says if you want to report something join the discord i added "or report a issue on the github page at https://github.com/Olexorus/WitherAC/issues" but fianlly heres the config link xd https://pastebin.com/FzTyapBL

**Comment by Olexorus** [comment]
If you're alone on a server, or only a few people are online, then you can remove the delay, but on bigger servers (20-30 players), without a delay there'll be some spam, that's why that option is there.

I don't want to add an autoban yet, because the plugin isn't relieable enough imo.

Normally the tps config isn't absolutely necessary, and since it completely disables checks it should only be used when needed, that's why it's disabled by default (except in the packet speed check, because it's not really possible for this check to be relieable when there's severe lag).

The point of the violation expiration is to differentiate between players who have joined 20 seconds ago and already got 10 violations, and those who have played for 5 hours and got the same amount of violations in that time. I think it's really useful since there will always be an occasional false positive, and they'll add up over time without an expiration.

All of these options can be argued about (that's why they're in the config, if there was a clear "best" option I wouldn't have put them there), I tried to optimize the default config to work for most servers fairly well, some of your optimizations might make sense on some servers, but be useless on others, for example setting the min tps to 10 or 15 might be a good idea on a server that's constantly at 18-19 tps, but add that to a server that often has lower tps (which is a lot of the servers since 1.13 and 1.14 destroyed the performance), and the anti cheat becomes useless half of the time.

I hope I answered all the important points you wrote, please use punctuation and new lines in the future, it's extremely hard to read your text.

**Comment by Olexorus** [comment]
Oh, and I'll add your suggestion about being able to disable the violation expiration, I don't know why I haven't added that already.
