### ISSUE TITLE
Packetspoof False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#30]
i was just elytraing around and i randomly hit the ground going fast with it and it falsed packetspoof idk why https://streamable.com/qi7d9

**Comment by Olexorus** [comment]
Since there was a pretty big pause in WACs development I've decided to close all currently open issues. A bug list for an Anti Cheat will never be complete anyways, so I'd rather only have the things I'm plannign to work on soon on the issue tracker.
If this issue still exists on the latest version and you think it's important for me to fix you can of course reopen it.
