### ISSUE TITLE
Fly / Illegal Movement False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#33]
if your looking straight down and when you jump enderpearl at the ground and keep doing that sometimes you false fly this was done on minecraft version 1.14.4 btw heres a video of it https://streamable.com/hqy14

**Comment by Olexorus** [comment]
Since there was a pretty big pause in WACs development I've decided to close all currently open issues. A bug list for an Anti Cheat will never be complete anyways, so I'd rather only have the things I'm plannign to work on soon on the issue tracker.
If this issue still exists on the latest version and you think it's important for me to fix you can of course reopen it.
