### ISSUE TITLE
Angle / Killaura False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Olexorus/WitherAC#36]
if you have a trident with riptide 1 2 or 3 and its raining and you have a mob or animal or something hold left click on the trident to power it up aim at a mob and let go cause it will for some reason act like it attacks the mob or animal and will false Angle / Killaura minecraft version is 1.15.1

**Comment by Olexorus** [comment]
Since there was a pretty big pause in WACs development I've decided to close all currently open issues. A bug list for an Anti Cheat will never be complete anyways, so I'd rather only have the things I'm plannign to work on soon on the issue tracker.
If this issue still exists on the latest version and you think it's important for me to fix you can of course reopen it.
