### ISSUE TITLE
Pillaring up sometimes kicks you off the block

### ISSUE THREAD

**Issue by WaifuBeforeLaifu** [Olexorus/WitherAC#50]
So I'm looking straight down and placing blocks under me while jumping to pillar up and sometimes it kicks me off the tower. Sometimes the violation is listed as "Packet Spoof" and sometimes its "Fly/Illegal Movement." 
WAC Version: 0.21.2
Paper: 1.16.1 v98

**Comment by Floffah** [comment]
according to [this update](https://www.spigotmc.org/resources/wither-anti-cheat-1-13-x-1-16-x-paper-tuinity-support-free-accurate-optimized-anti-cheat.68657/update?update=294347) it was fixed but i still get this issue and its as if the block gets placed while the player is still in the block and only started happening as soon as WAC was added

**Comment by Jaymate123** [comment]
Has this Anticheat been abandoned? The anticheat claims it shouldn't need a config because false detections should be fixed, but 1. Sometimes you want to use the anticheat but disable a check until it's fixed, better a partial anticheat then none. 2. The Anticheat isn't even being updated so....

This anticheat is useless on my server because of the constant fly/illegal movement violations.

**Comment by Olexorus** [comment]
Fixed in 0.22.0
