### ISSUE TITLE
Entities bypass water walk detection

### ISSUE THREAD

**Issue by loicbersier** [Olexorus/WitherAC#6]
Walking on water while riding entities doesn't trigger WitherAC

Example with horse: https://streamable.com/gfx1z
Example with boat: https://streamable.com/ktzwr

WAC v0.14.1
WAC config.yml https://pastebin.com/raw/rvJS9FC1
papermc 151 on 1.14.4
List of plugins: ![image](https://user-images.githubusercontent.com/36051669/63109327-3dd05900-bf89-11e9-8b25-4f599856fb8c.png)

(also, nice plugins work a lot better than other i have tried good job)

**Comment by loicbersier** [comment]
Updated WAC to v0.14.2 and it have the same result

**Comment by Olexorus** [comment]
I know, moving while riding entities works really different from moving normally, because of this, wac just excludes players riding horses, minecarts etc. atm. I plan to add support for these in the future.

**Comment by Olexorus** [comment]
Since there was a pretty big pause in WACs development I've decided to close all currently open issues. A bug list for an Anti Cheat will never be complete anyways, so I'd rather only have the things I'm plannign to work on soon on the issue tracker.
If this issue still exists on the latest version and you think it's important for me to fix you can of course reopen it.
