### ISSUE TITLE
Entities bypass speed detection

### ISSUE THREAD

**Issue by loicbersier** [Olexorus/WitherAC#7]
Entities bypass speed detection

Example with horse: https://streamable.com/7hrc8
Example with boat: https://streamable.com/tafdr

WAC v0.14.2
WAC config.yml https://pastebin.com/raw/rvJS9FC1
papermc 161 on 1.14.4
List of plugins: ![image](https://user-images.githubusercontent.com/36051669/63109327-3dd05900-bf89-11e9-8b25-4f599856fb8c.png)

**Comment by Olexorus** [comment]
I know, moving while riding entities works really different from moving normally, because of this, wac just excludes players riding horses, minecarts etc. atm. I plan to add support for these in the future.

**Comment by Olexorus** [comment]
Since there was a pretty big pause in WACs development I've decided to close all currently open issues. A bug list for an Anti Cheat will never be complete anyways, so I'd rather only have the things I'm plannign to work on soon on the issue tracker.
If this issue still exists on the latest version and you think it's important for me to fix you can of course reopen it.
